### ISSUE TITLE
Create ports tree

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [Andy-Python-Programmer/aero#37]
Umm, I dont think its exactly wise to put things like doom in the sysroot, you should create a ports tree where you can access these packages using the internet to download the source, then compiling it(and create eth drivers). Just a thought.
(I also dont want to cherry pick what commits I want to add to uwux, im building other projects rn)

**Comment by Andy-Python-Programmer** [comment]
It would be nice to have a `config.toml` where we could enable or disable ports that we want to build. For example:

```toml
# ---- config.toml -----
[sysroot]
# by default no ports will be enabled.
ports = ["gcc", "rust", "ripgrep"]
````

and this config file will be read by `aero.py` when called with `--sysroot` and will make `xbstrap` only build those enabled ports. Pretty nice idea actually.
